---
title: "week2"
author: "AmyHs"
date: "2018年4月8日"
output: html_document
---
#week_2 Task
-建立一命名為week_2(or task_2, hw_2)的資料夾。
<br>-完成一支網站爬蟲上傳至資料夾中，繳交三種類型檔案(.R, .Rmd, .html)。

##決定來看看IMDb上評分最高的250部電影有哪些，列入之後的待看清單
##先載入要用的套件
```{r,include=T}
library(rvest)
library(magrittr)
```

##取得網址
```{r,include=T}
url<-read_html("http://www.imdb.com/chart/top?pf_rd_m=A2FGELUUNOQJNL&pf_rd_p=4da9d9a5-d299-43f2-9c53-f0efa18182cd&pf_rd_r=17BXDA2B9WWHC96K70QD&pf_rd_s=right-4&pf_rd_t=15506&pf_rd_i=toptv&ref_=chttvtp_ql_3")
```

##取得電影top250，想要電影縮圖、名稱、個別電影網址、還有評分
```{r,include=T}
movieimg<-html_nodes(url,".posterColumn")%>%html_nodes("img")%>%html_attr("src")
title<-html_nodes(url,".titleColumn")%>%html_text(.,trim = T)
movieUrl<-html_nodes(url,".titleColumn")%>%html_nodes("a")%>%html_attr("href")%>%paste("http://www.imdb.com",.)
rating<-html_nodes(url,".imdbRating")%>%html_text()
```

##做成表格
```{r,include=T}
df<-data.frame(image = movieimg, movie = title, rating, url = movieUrl, stringsAsFactors=FALSE)
```

##來做一個不需要網址、圖片只需要電影和評分的表格
```{r,include=T}
df_for_reading<-df[,c(-1,-4)]
```

##存成csv
```{r,results = "hide"}
setwd("C:/Users/b0520/Desktop/csx_R_course")
write.table(df_for_reading,file = "TopMovies.csv",sep = ",",row.names = F)
```


